# Generated by Django 4.2.11 on 2026-03-20 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='input/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='output/')),
                ('filter_type', models.CharField(choices=[('canny', 'Canny Edge Detection'), ('sobel', 'Sobel Filter'), ('laplacian', 'Laplacian Filter'), ('contour', 'Contour Detection'), ('histogram_eq', 'Histogram Equalization'), ('contrast_stretch', 'Contrast Stretching'), ('brightness_contrast', 'Brightness / Contrast'), ('gaussian_blur', 'Gaussian Blur'), ('median_filter', 'Median Filter'), ('document_scanner', 'Document Scanner'), ('unsharp_mask', 'Unsharp Mask'), ('auto_white_balance', 'Auto White Balance')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('param_threshold1', models.IntegerField(blank=True, null=True)),
                ('param_threshold2', models.IntegerField(blank=True, null=True)),
                ('param_ksize', models.IntegerField(blank=True, null=True)),
                ('param_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('param_brightness', models.FloatField(blank=True, null=True)),
                ('param_contrast', models.FloatField(blank=True, null=True)),
                ('param_strength', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
